# Load data
```{r}
library(R.matlab)
mat_data <- readMat("VectLB19922008.mat")
df <- as.data.frame(mat_data$Vect)

# add column names
colnames(df) <- unlist(mat_data$labels)

# data of BATS location
bats <- df[(df$latitude>=31) & (df$latitude<=33) & (df$longitude<=-63) & (df$longitude>=-65), ]

# remove lat and long from bats data
bats <- bats[, -which(names(bats) %in% c("latitude", "longitude"))]
```

# Heatmap graph for first A4
```{r}
#1992
bats1992 <- bats[(bats$year==1992), c("CHL 1", "CHL 2", "CHL 3", "CHL 4", "CHL 5", "CHL 6", "CHL 7", "CHL 8", "CHL 9", "CHL 10", "CHL 11", "CHL 12", "CHL 13", "CHL 14", "CHL 15", "CHL 16", "CHL 17", "CHL 18", "5days")]

tmp <- c()
for (i in 1:nrow(bats1992)) {
  tmp <- c(tmp, as.numeric(bats1992[i, -19]))
}

plot1992 <- expand.grid(depth=1:18, `5days`=1:73)
plot1992$CHL <- tmp

library(ggplot2)
`5 days` <- plot1992$`5days`
`Depth level` <- plot1992$depth
CHL <- plot1992$CHL
gg1992 <- ggplot(plot1992, aes(`5 days`, `Depth level`, fill=CHL)) + geom_tile() + scale_fill_gradientn(colors = rainbow(7), limits=c(0,1.5), breaks=seq(0,1.5,0.25)) + scale_y_reverse() + coord_fixed() + ggtitle("1992")

# -----

#library(gridExtra)
#grid.arrange(gg1992, gg1996, gg2000, gg2004, nrow=2, ncol=2)
```

???

```{r}
library(corrplot)
corrplot(cor(XandY_dateConverted), method="color", type="lower", number.cex=.7, addCoef.col = "black")
```

